### ISSUE TITLE
Hackathon114: cbor grammar error on SUIT_Parameters 

### ISSUE THREAD

**Issue by mcd500** [suit-wg/manifest-spec#65]
This is spawned from https://github.com/ietf-teep/teep-protocol/issues/198 when trying to run cddl grammar check.

It shows log from cddl tool as follow.
```
	  4: from /var/lib/gems/2.5.0/gems/cddl-0.8.29/lib/cddl.rb:1418:in `block in type_collect'
	  3: from /var/lib/gems/2.5.0/gems/cddl-0.8.29/lib/cddl.rb:1352:in `type1'
	  2: from /var/lib/gems/2.5.0/gems/cddl-0.8.29/lib/cddl.rb:1286:in `type2'
	  1: from /var/lib/gems/2.5.0/gems/cddl-0.8.29/lib/cddl.rb:1259:in `type_recall'
/var/lib/gems/2.5.0/gems/cddl-0.8.29/lib/cddl.rb:1077:in `rule_lookup': SUIT_Parameters not a type [:grpchoice, [[:member, 1, 1, [:int, 1], [:type1, [:anno, :size, [:prim, 2], [:int, 16]], [:prim, 6, 112, [:prim, 2]]]]], [[:member, 1, 1, [:int, 2], [:anno, :size, [:prim, 2], [:int, 16]]]], [[:member, 1, 1, [:int, 3], [:anno, :cbor, [:prim, 2], [:array, [:member, 1, 1, [:text, "suit-digest-algorithm-id"], [:type1, [:int, -16], [:int, -18], [:int, -43], [:int, -44], [:int, -45]]], [:member, 1, 1, [:text, "suit-digest-bytes"], [:prim, 2]]]]]], [[:member, 1, 1, [:int, 14], [:prim, 0]]], [[:member, 1, 1, [:int, 5], [:prim, 0]]], [[:member, 1, 1, [:int, 21], [:prim, 3]]], [[:member, 1, 1, [:int, 22], [:prim, 0]]], [[:member, 1, 1, [:int, 23], [:prim, 2]]], [[:member, 1, 1, [:int, 24], [:anno, :size, [:prim, 2], [:int, 16]]]], [[:member, 1, 1, [:prim, 1], [:type1, [:type1, [:prim, 0], [:prim, 1]], [:type1, [:prim, 7, 20], [:prim, 7, 21]], [:prim, 3], [:prim, 2]]]], [[:member, 1, 1, [:int, 12], [:type1, [:prim, 7, 20], [:prim, 7, 21]]]], [[:member, 1, 1, [:int, 13], [:type1, [:prim, 7, 20], [:prim, 7, 21]]]]] (RuntimeError)
```
This is the definition of SUIT_Parameters in the draft-ietf-suit-manifest.cddl.
```
SUIT_Parameters //= (suit-parameter-class-identifier => RFC4122_UUID)
SUIT_Parameters //= (suit-parameter-image-digest
    => bstr .cbor SUIT_Digest)
SUIT_Parameters //= (suit-parameter-image-size => uint)
SUIT_Parameters //= (suit-parameter-component-slot => uint)
```

Do we need extra definition for SUIT_Parameters to be treated as a group in cddl?
Or it could be misleading log from cddl tool.

**Comment by dthaler** [comment]
Perhaps SUIT_Parameters was intended to be an extensible socket?  If so SUIT_Parameters should be $$SUIT_Parametes

**Comment by bremoran** [comment]
Based on the error from the cddl tool, this looks to me like a broken dependency between SUIT_Report (which consumes SUIT_Parameters) and SUIT_Manifest.

**Comment by dthaler** [comment]
The broken dependency is because SUIT_Report needs to also change to use $$SUIT_Parameters instead of SUIT_Parameters.  Same with draft-ietf-suit-trust-domains and draft-ietf-suit-firmware-encryption and draft-ietf-suit-update-management.
